services:
  spring:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "80:8177"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=vpn
    depends_on:
      - db

  gen-spring:
    build:
      context: .
      dockerfile: gen-spring.dockerfile 
    ports:
      - "90:8080"

  db:
    image: postgres:18
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=vpn
      - PGDATA=/var/lib/pgsql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/pgsql

  db-adminer:
    image: adminer
    restart: no
    ports:
      - "8080:8080"

volumes:
  data:
