services:
  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:5173
    environment:
      - VITE_API_HOST=spring
      - VITE_API_PORT=8177
    depends_on:
      - spring

  spring:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=vpn
    depends_on:
      - db

  gen-spring:
    build:
      context: .
      dockerfile: gen-spring.dockerfile 
    ports:
      - 90:8080

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=vpn
      - PGDATA=/var/lib/pgsql
    volumes:
      - ./initdb.d:/docker-entrypoing-initdb.d
      - pgdata:/var/lib/pgsql

  db-adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080

volumes:
  pgdata:
