openapi: "3.0.3"
info:
  title: WireGuard Manager
  version: "0.1.1"
paths:
  /users:
    get:
      summary: Get users with optional limiting
      operationId: getUsers
      parameters:
        - name: limit
          in: query
          description: Limit of users to retrieve
          required: false
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create the new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserContent"
              required:
                - username
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Schema validation failed
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{userId}:
    get:
      summary: Get an existing user
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Not found
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update an existing user      
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: ID of user to update
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserContent"
              required:
                - username
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Schema validation failed
        "404":
          description: Not found
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Patch an existing user
      operationId: patchUser
      parameters:
        - name: userId
          in: path
          description: ID of user to patch
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserContent"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Schema validation failed
        "404":
          description: Not found
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete an existing user
      operationId: deleteUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to remove
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      responses:
        "204":
          description: Success
        default:
          description: Internal error

components:
  schemas:
    Error:
      description: Server error info
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: -1024
        msg:
          type: string
          maxLength: 256
          example: unknown error
      required:
        - code

    User:
      description: User entity
      allOf:
        - type: object
          properties:
            id:
              $ref: "#/components/schemas/UserId"
        - $ref: "#/components/schemas/UserContent"
      required:
        - id
        - username

    UserId:
      description: ID of a user
      type: integer
      format: uint64

    UserContent:
      description: Info of a user
      type: object
      properties:
        username:
          type: string
          pattern: "^[a-zA-Z_][a-zA-Z0-9_-]{2,31}$"
          example: best_user-1
        contacts:
          type: object
          properties:
            email:
              type: string
              format: email
              example: user@example.com
