openapi: "3.0.3"
info:
  title: WireGuard Manager
  version: "0.1"
paths:
  /users:
    post:
      summary: Create the new user
      description: |-
        Creates the new user with prefered ID
        (server-generated on a collision)
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{userId}:
    get:
      summary: Get an existing user
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Not found
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update an existing user      
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: ID of user to update
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Not found
        default:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete an existing user
      operationId: deleteUserById
      parameters:
        - name: userId
          in: path
          description: ID of user to remove
          required: true
          schema:
            $ref: "#/components/schemas/UserId"
      responses:
        "204":
          description: Success
        default:
          description: Internal error

components:
  schemas:
    Error:
      description: Server error info
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: -1024
        msg:
          type: string
          maxLength: 256
          example: unknown error
      required:
        - code

    UserId:
      description: ID of a user
      type: integer
      format: uint64

    User:
      description: Info of a user
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UserId"
        username:
          type: string
          pattern: "^[a-zA-Z0-9_-]{3,20}$"
        contacts:
          type: object
          properties:
            email:
              type: string
              format: email
      required:
        - id
        - username
