services:
  javadev:
    image: mcr.microsoft.com/devcontainers/java:dev-25-jdk-trixie
    network_mode: service:db
    volumes:
      - ..:/workspaces/wg-mgr:cached
    environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    command: sleep infinity

  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ../initdb.d:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
        - PGDATA=/var/lib/postgresql/data

volumes:
  pg-data:
