name: backend testing
on: [pull_request]
jobs:
  test-spring:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install maven
        run: sudo apt update && sudo apt install -y maven
      - name: Module tests for the Spring backend service
        run: mvn -ff -Dtest=VpnUserServiceTest test
        working-directory: backend
